global:
  scrape_interval: 3s

rule_files:
  - 'alert.rules.yml'
  
scrape_configs:
  - job_name: 'service-1_and_2'
    static_configs:
      - targets: ['localhost:4001','localhost:4003']  # Replace with your Node.js app container name or IP address